### ISSUE TITLE
kubernetes - update for 1.5

### ISSUE THREAD

**Issue by mlbiam** [TremoloSecurity/wiki#2]
don't need initial boot-strap

**Comment by mlbiam** [comment]
add new role binding def too

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-role
  namespace: new-namespace
rules:
- apiGroups: ["*"]
  nonResourceURLs: ["*"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-binding
  namespace: new-namespace
subjects:
- kind: Group
  name: new-namespace-admin
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: admin-role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: viewer-role
  namespace: new-namespace
rules:
- apiGroups: ["*"]
  nonResourceURLs: ["*"]
  verbs: ["get","view","list","watch"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","view","list","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: viewer-binding
  namespace: new-namespace
subjects:
- kind: Group
  name: new-namespace-viewer
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: viewer-role
```
